version: '3.7'

services:
  api:
    build:
      context: .
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    networks:
      - homelibrary
    depends_on:
      - db
  db:
    build:
      context: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PG_DATA=${POSTGRES_DB_DATA_PATH}
    volumes:
      - db-data:${POSTGRES_DB_DATA_PATH}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: unless-stopped
    networks:
      - homelibrary

networks:
  homelibrary:
    driver: bridge
volumes:
  db-data:
